// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtaI_bRF4mDc6aCVHKYs87Ns6K9W5Md-o',
    appId: '1:1080864880571:ios:44d9be7c1f46f7d003369e',
    messagingSenderId: '1080864880571',
    projectId: 'honey-project-5749b',
    storageBucket: 'honey-project-5749b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB43SVJ77phtApy-0E0WZf9PJ7Om9cGsTQ',
    appId: '1:1080864880571:ios:44d9be7c1f46f7d003369e',
    messagingSenderId: '1080864880571',
    projectId: 'honey-project-5749b',
    storageBucket: 'honey-project-5749b.appspot.com',
    iosClientId:
        '1080864880571-rnmla9apntim6ob2c6q4gm0stghqf9is.apps.googleusercontent.com',
    iosBundleId: 'com.example.honey',
  );
}
